!obj:pylearn2.train.Train {
    dataset: &train !obj:readCSVforPylearn.CSVDataset {
        path : 'train.csv',
        start : 0,
        stop : 50000,
        one_hot : True,
        expect_headers : True
}
,
    model: !obj:pylearn2.models.softmax_regression.SoftmaxRegression {
        n_classes: 10,
        irange: 0.,
        nvis: 784,
}
,
    algorithm: !obj:pylearn2.training_algorithms.bgd.BGD {
        batch_size: 10000,
        line_search_mode: 'exhaustive',
        conjugate: 1,
        monitoring_dataset:
            {
                'train' : *train,
                'valid' : !obj:readCSVforPylearn.CSVDataset {
                              path : 'train.csv',
                              start : 50000,
                              stop : 60000,
                              one_hot : True,
                              expect_headers : True
                },
                'test'  : !obj:readCSVforPylearn.CSVDataset {
                              path : 'test.csv',
                              one_hot : True,
                              expect_headers : True,
                              expect_labels : False
                }
            },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_y_misclass"
        }
    }
,
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "softmax_regression_best.pkl"
        },
    ],
    save_path: "softmax_regression.pkl",
    save_freq: 1    
}